### ISSUE TITLE
Emails not sending due to missing Mandrill templates

### ISSUE THREAD

**Issue by fusion2004** [orientation/orientation#141]
It looks like my delayed job process is crashing when it tries to send emails because the mailer uses Mandrill templates that I do not have:

```
2015-06-18T12:32:47.039610+00:00 app[worker.1]: [Worker(host:3e56ee33-6c20-4348-bddd-f1e67f867065 pid:3)] Starting job worker
2015-06-18T12:32:47.039684+00:00 app[worker.1]: 2015-06-18T12:32:47+0000: [Worker(host:3e56ee33-6c20-4348-bddd-f1e67f867065 pid:3)] Starting job worker
2015-06-18T12:32:47.106101+00:00 app[worker.1]:   Delayed::Backend::ActiveRecord::Job Load (3.5ms)  UPDATE "delayed_jobs" SET locked_at = '2015-06-18 12:32:47.100466', locked_by = 'host:3e56ee33-6c20-4348-bddd-f1e67f867065 pid:3' WHERE id IN (SELECT  "delayed_jobs"."id" FROM "delayed_jobs" WHERE ((run_at <= '2015-06-18 12:32:47.039760' AND (locked_at IS NULL OR locked_at < '2015-06-18 08:32:47.039798') OR locked_by = 'host:3e56ee33-6c20-4348-bddd-f1e67f867065 pid:3') AND failed_at IS NULL)  ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
2015-06-18T12:32:47.130885+00:00 app[worker.1]: [Worker(host:3e56ee33-6c20-4348-bddd-f1e67f867065 pid:3)] Job SendArticleRottenJob (id=1) RUNNING
2015-06-18T12:32:47.130972+00:00 app[worker.1]: 2015-06-18T12:32:47+0000: [Worker(host:3e56ee33-6c20-4348-bddd-f1e67f867065 pid:3)] Job SendArticleRottenJob (id=1) RUNNING
2015-06-18T12:32:47.237640+00:00 app[worker.1]:   Article Load (1.6ms)  SELECT  "articles".* FROM "articles" WHERE "articles"."id" = $1 LIMIT 1  [["id", 1]]
2015-06-18T12:32:47.571076+00:00 app[worker.1]: rake aborted!
2015-06-18T12:32:47.571136+00:00 app[worker.1]: Mandrill::UnknownTemplateError: No such template "article-rotten-update"
2015-06-18T12:32:47.571520+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/mandrill-api-1.0.53/lib/mandrill.rb:92:in `cast_error'
2015-06-18T12:32:47.571522+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/mandrill-api-1.0.53/lib/mandrill.rb:37:in `call'
2015-06-18T12:32:47.571524+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/mandrill-api-1.0.53/lib/mandrill/api.rb:921:in `send_template'
2015-06-18T12:32:47.571526+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/mandrill_mailer-0.5.1/lib/mandrill_mailer/template_mailer.rb:116:in `deliver'
2015-06-18T12:32:47.570849+00:00 app[worker.1]:   SQL (2.1ms)  UPDATE "delayed_jobs" SET "locked_by" = NULL, "locked_at" = NULL WHERE "delayed_jobs"."locked_by" = $1  [["locked_by", "host:3e56ee33-6c20-4348-bddd-f1e67f867065 pid:3"]]
2015-06-18T12:32:47.571528+00:00 app[worker.1]: /app/app/jobs/send_article_rotten_job.rb:4:in `perform'
2015-06-18T12:32:47.571530+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
2015-06-18T12:32:47.571532+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
2015-06-18T12:32:47.571533+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
2015-06-18T12:32:47.571534+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
2015-06-18T12:32:47.571536+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
2015-06-18T12:32:47.571537+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
2015-06-18T12:32:47.571539+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
2015-06-18T12:32:47.571540+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
2015-06-18T12:32:47.571541+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
2015-06-18T12:32:47.571543+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
2015-06-18T12:32:47.571544+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
2015-06-18T12:32:47.571546+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
2015-06-18T12:32:47.571547+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
2015-06-18T12:32:47.571548+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
2015-06-18T12:32:47.571549+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
2015-06-18T12:32:47.571551+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
2015-06-18T12:32:47.571552+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
2015-06-18T12:32:47.571553+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
2015-06-18T12:32:47.571554+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
2015-06-18T12:32:47.571556+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
2015-06-18T12:32:47.571557+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
2015-06-18T12:32:47.571558+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
2015-06-18T12:32:47.571559+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
2015-06-18T12:32:47.571560+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
2015-06-18T12:32:47.571561+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
2015-06-18T12:32:47.571563+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
2015-06-18T12:32:47.571564+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
2015-06-18T12:32:47.571565+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
2015-06-18T12:32:47.571566+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
2015-06-18T12:32:47.571567+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
2015-06-18T12:32:47.571568+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
2015-06-18T12:32:47.571570+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
2015-06-18T12:32:47.571571+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
2015-06-18T12:32:47.571572+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
2015-06-18T12:32:47.571574+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
2015-06-18T12:32:47.571575+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
2015-06-18T12:32:47.571580+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
2015-06-18T12:32:47.571581+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
2015-06-18T12:32:47.571582+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
2015-06-18T12:32:47.571583+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
2015-06-18T12:32:47.571585+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
2015-06-18T12:32:47.571586+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
2015-06-18T12:32:47.571587+00:00 app[worker.1]: /app/vendor/bundle/ruby/2.0.0/gems/delayed_job-4.0.6/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
2015-06-18T12:32:47.571589+00:00 app[worker.1]: Tasks: TOP => jobs:work
2015-06-18T12:32:47.571599+00:00 app[worker.1]: (See full trace by running task with --trace)
```

Also, this error completely crashes the worker process, and is not reporting to Bugsnag like the web process is.

**Comment by fusion2004** [comment]
Any chance of getting an export of the templates added to the repo?
I could just go make my own, but if there's official-ish ones I'd rather use those.

**Comment by olivierlacan** [comment]
@fusion2004 They're real basic plaintext but it's a good idea. :-)

**Comment by olivierlacan** [comment]
@fusion2004 Done and also added a section about this in the README: https://github.com/orientation/orientation/blob/master/README.md#transactional-emails-with-mandrill

I'm guessing you had your Mandrill settings filled out, otherwise emails should not be sent at all, right?

I'm going to need to rescue from these exceptions somewhere and display a useful error message in the logs probably. Interested in making a PR for this by any chance?

**Comment by fusion2004** [comment]
Sure! I may not have time until the weekend, but I can take a look at it.
